parameters:
  cors.config:
    allowedHeaders: {}
    allowedMethods: {}
    allowedOrigins:
      - "*"
    enabled: false
    exposedHeaders: false
    maxAge: false
    supportsCredentials: false
  factory.keyvalue: {}
  factory.keyvalue.expirable: {}
  filter_protocols:
    - http
    - https
    - ftp
    - news
    - nntp
    - tel
    - telnet
    - mailto
    - irc
    - ssh
    - sftp
    - webcal
    - rtsp
  http.response.debug_cacheability_headers: false
  renderer.config:
    auto_placeholder_conditions:
      contexts:
        - session
        - user
      max-age: 0
      tags: {}
    required_cache_contexts:
      - "languages:language_interface"
      - theme
      - user.permissions
  session.storage.options:
    cookie_lifetime: 2000000
    gc_divisor: 100
    gc_maxlifetime: 200000
    gc_probability: 1
  twig.config:
    auto_reload: false
    cache: true
    debug: false
